### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by raucao** [67P/hyperchannel#1]
Implement full-screen mode for whole app (just request fullscreen for application element). Will be nice on second screens.

**Comment by skddc** [comment]
https://www.npmjs.com/package/ember-fullscreen

**Comment by raucao** [comment]
In hindsight, this is really the weirdest issue for being the very first one. I'm going to close this for now, as I don't see how this is important or relevant anytime soon. Could it be that not all browsers had normal fullscreen modes/buttons back then?
