### ISSUE TITLE
User's own messages don't show up in other tabs/windows

### ISSUE THREAD

**Issue by galfert** [67P/hyperchannel#117]
When having Hyperchannel open in multiple tabs or browser windows with the same user, the user's message only shows up in the tab the user wrote the message in.

That's because we currently discard the Sockethub messages for the user and only use the submitted message directly.

One idea was to just show the message in a lighter gray when sent, and then show it normally when it was received, indicating that others should have received the message as well now.

**Comment by skddc** [comment]
> One idea was to just show the message in a lighter gray when sent, and then show it normally when it was received, indicating that others should have received the message as well now.

Yes, that's part of making Hyperchannel work well on intermittent/mobile connections anyway. And it'll automatically be possible, when we start diffing/syncing logs to one's own RS.

**Comment by skddc** [comment]
I removed the bug label, because this is just not implemented yet. There's no actual bug in our current code.
