### ISSUE TITLE
Channel is shown as connected too early

### ISSUE THREAD

**Issue by galfert** [67P/hyperchannel#118]
We currently show channels as connected when we receive the `completed` event for the `join` message from Sockethub. But that just indicates that the `join` was sent to IRC now.

When having a different IRC client open at the same time, one can see that the actual moment a user is joining a channel, is the moment Hyperchannel receives the first userlist from Sockethub.

So should we rather use that message to mark the channel as connected?

**Comment by skddc** [comment]
Yes, good idea.

We also need visual indication of channel connection status in the channel UI itself, esp. on mobile screens. But that's a different issue.
