### ISSUE TITLE
Missing channel userlist when reloading browser

### ISSUE THREAD

**Issue by galfert** [67P/hyperchannel#127]
For all channels that the user already joined, after a browser reload the userlist of those channels is empty.

We probably need to do something similar to IRC, where we send an `observe` activity for the channel's user attendance after joining.

**Comment by galfert** [comment]
XMPP calls it "[Querying for Room Items](https://xmpp.org/extensions/xep-0045.html#disco-roomitems)".

**Comment by skddc** [comment]
Cool, so that means the userlist already works in XMPP before a reload?

**Comment by galfert** [comment]
Yes, when joining a channel for the first time you should see the userlist.

**Comment by galfert** [comment]
Needs sockethub/sockethub-platform-xmpp#7
