### ISSUE TITLE
Possible to not destroy channel components?

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#144]
It's a bit of a performance issue to destroy the channels when switching between them, and re-populate all messages when switching to one. Also, there's currently a scroll animation, which would make fast-cycling through channels pretty annoying (and I'm not sure loading the messages and then jumping down is much better).

Is there any chance we can keep channel content/markup loaded, until one closes the tab or leaves a channel?

**Comment by galfert** [comment]
Just from my current knowledge I would say it's not possible. But I'll do some research to find out if there is any way.

**Comment by skddc** [comment]
It's of course possible, if we don't instantiate a component per channel, but keep the markup around and just show/hide via CSS or JS. Question is what the best and most efficient way would be.

**Comment by skddc** [comment]
Duplicate of #92
