### ISSUE TITLE
Keyboard shortcut for fast-switching channels

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#148]
This is something I can't live without in my desktop IRC client. It supports ctrl-pgup/down for going up and down the channel list. Not sure what the best combo for a web app would be, and also not sure what a good compromise would be for users of all of macOS, Windows, GNOME and KDE.

**Comment by gregkare** [comment]
A shortcut to get to the next channel with an unread message would be super useful too (I use it all the time in my desktop IRC client)

**Comment by skddc** [comment]
What's the shortcut for that in your client?

**Comment by gregkare** [comment]
Alt+a (weechat): "Switch to next buffer with activity (with priority: highlight, message, other)."

**Comment by skddc** [comment]
I think ctrl-arrowup/down would be an okay combo. Does that clash with anyone's OS's defaults in their browser?

**Comment by gregkare** [comment]
Ctrl-arrowleft/right sounds good to me!

**Comment by galfert** [comment]
On OS X scrolling is done via cmd-up/down and ctrl-up/down is opening window exposés.

There is nothing happening for ctrl-left/right, so that should work.

**Comment by galfert** [comment]
> There is nothing happening for ctrl-left/right, so that should work.

Actually, in macOS, <kbd>ctrl</kbd>-<kbd>left</kbd>/<kbd>right</kbd> switches between spaces. So I think that one's out as well. How about using <kbd>cmd</kbd> instead of <kbd>ctrl</kbd> in macOS?

**Comment by skddc** [comment]
> How about using ctrl+shift+up/down?

I'd prefer ctrl+left/right, but how about we make it system-specific? Or let users choose their own and have ctrl+shift+up/down as default. In any case, the latter should work on all systems.
