### ISSUE TITLE
Switch to SVG icons instead of icon font

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#154]
When I wanted to add a new icon the other day, I found out that we still use some ancient custom icon font, created on Icomoon, for which I don't even have an account anymore.

SVG icons are generally easier to work with, can be styled with CSS, animated, and so on. I came up with an easy way to use them in Ember last year: placing the icon's SVG in a `app/templates/icons/my-icon.hbs` file, and then simply including them as a partial via `{{partial "my-icon"}}`. (See https://gitlab.com/skddc/inspektor for a real-world example.)

Any comments/opinions/links on beautiful icon sets would be useful for this one, of course.

**Comment by skddc** [comment]
Once this is done, we can replace one of the two icons in the purple channel header with an icon for leaving the channel (see discussion in #104). We can also add another icon bar in the bottom left for global/user-specific actions (e.g. app settings) and make the icons in the top right be a tab switcher purely for the current channel's functionality (files, user list, channel settings, etc.).

**Comment by galfert** [comment]
I couldn't find it just now, but I think I read somewhere that a template-only component should perform the same way as a template.

**Comment by skddc** [comment]
Ah, that makes sense actually. If there's no component code specified, then the framework can treat it like a partial. Thanks.

**Comment by skddc** [comment]
@galfert Another terrible negative about that approach is that it encloses every single icon in an Ember div. So if you have an `<svg>` in an `<a>`, Ember will throw a `<div>` between the two. That's some abysmal markup for just adding an HTML partial.

**Comment by skddc** [comment]
Regarding icon sets, https://feathericons.com seems nice. Or just plain Material icon: https://material.io/tools/icons/ for example.

**Comment by galfert** [comment]
FYI: there is an [actual RFC to deprecate partials](https://github.com/emberjs/rfcs/pull/449) now. And it even states that partials "perform poorly in comparison to components".

**Comment by skddc** [comment]
Yeah, I already replaced them with components in some other Ember apps.
