### ISSUE TITLE
New activity-streams URL in Sockethub 3.0

### ISSUE THREAD

**Issue by gregkare** [67P/hyperchannel#161]
I deployed a test instance of [sockethub 3.0.1](https://github.com/sockethub/sockethub/tree/v3.0.1) using the latest node LTS version (2.0.5 doesn't work with node 10)

In Sockethub 3.0, the activity streams JS file is available under https://sockethub.kosmos.org:10550/activity-streams.min.js instead of https://sockethub.kosmos.org:10550/activity-streams.js, so hyperchannel doesn't work anymore

Apart from that hyperchannel appears to work with sockethub 3

**Comment by gregkare** [comment]
Wouldn't it make more sense to vendor these dependencies into hyperchannel instead?

**Comment by skddc** [comment]
No, because Hyperchannel cannot know which version of Sockethub you are going to connect. Also, Sockethub should provide unminified client code, as it did before.

**Comment by gregkare** [comment]
OK, I'll open an issue in sockethub then

**Comment by gregkare** [comment]
This was fixed by #165
