### ISSUE TITLE
Add partial rendering for user list

### ISSUE THREAD

**Issue by galfert** [67P/hyperchannel#163]
Similar to #92, opening a channel with a lot of users (e.g. #debian on Freenode) is slow, because it takes so long to render the list of users.

To improve this, we can display only a certain number of users at first, and then display more when scrolling to the bottom of the list. See #162 for the implementation using an `InterectionObserver` for the channel's messages.

**Comment by skddc** [comment]
I think you don't mean "pagination", but partial rendering.
