### ISSUE TITLE
Identify via NickServ when password is set

### ISSUE THREAD

**Issue by raucao** [67P/hyperchannel#32]

**Comment by skddc** [comment]
@silverbucket We currently just get a different name set with no message to identify via NickServ. Do you know how this works with the IRC lib? I couldn't find an example in their docs.

**Comment by silverbucket** [comment]
Hmm, no, we can ask the irc-factory maintainer though, he's generally great about responding/fixing issues.

**Comment by raucao** [comment]
Closing in favor of #240
