### ISSUE TITLE
Add user to channel user list when they join the channel

### ISSUE THREAD

**Issue by galfert** [67P/hyperchannel#38]
Also show notification message about them joining.

**Comment by skddc** [comment]
This should already work. There was an issue with it stopping to work when reloading a lot, though (iirc).

**Comment by skddc** [comment]
Hmm, just saw a join message in the console and the user list didn't change, so I guess this hasn't been implemented yet after all.

**Comment by skddc** [comment]
@janlelis I think you finished this?

**Comment by skddc** [comment]
Bump. I think this already works.

**Comment by skddc** [comment]
Tested again, works.
