### ISSUE TITLE
Switch to Yarn (if possible)

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#42]
https://yarnpkg.com/

https://www.youtube.com/watch?v=PZ2QFmJ7h0A

**Comment by galfert** [comment]
Related issue to watch: https://github.com/ember-cli/ember-cli/issues/6341

**Comment by skddc** [comment]
However, not relevant for just using it today it seems:

> Yarn + ember-cli seem to work together, this issue is specifically for exploring ember-cli + yarn bundled together

**Comment by skddc** [comment]
I guess that means also using Yarn for `ember addon:install` and such.

**Comment by skddc** [comment]
They decided to remove Bower support entirely (so now it's multi-registry with, uhm, only npm): https://github.com/yarnpkg/yarn/pull/1441

**Comment by skddc** [comment]
They finally released a version that doesn't break Bower.

**Comment by galfert** [comment]
Unfortunately that new release seems to be pretty broken. There are already [a lot of issues](https://github.com/yarnpkg/yarn/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%5B0.17.0%5D) just about that new release.

When trying it out I was running into all kinds of weird errors (missing cache files, [error on linking dependencies](https://github.com/yarnpkg/yarn/issues/1853)).

**Comment by skddc** [comment]
We should probably but this on hold or in the backlog until a 1.0 then. Looks like it's not worth evaluating any longer until they get their act together.

**Comment by galfert** [comment]
Yes, I agree. Doesn't give much confidence the way it's working out so far.
