### ISSUE TITLE
Indicate channel activity in channel list

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#46]
The channel list should indicate activity for non-focussed channels.
- [x] Add class to element on activity
- [x] Remove class when focussing channel
- [x] Style unread-messages channel list item

**Comment by skddc** [comment]
I wonder if we should start with a read status right away, because that's what we're going to need anyway. I mean instead of just using "focussing the channel".

**Comment by galfert** [comment]
The number of unread messages next to the channel would be nice as well.

**Comment by skddc** [comment]
I'm not sure about that. Do you really have that in *any* team chat app you use or know? I think it migh be too much information (i.e. cluttering the UI with something that's not useful and takes away brain cycles from the important data). Also, I would assume actual implementation problems for getting that number right with e.g. IRC.

**Comment by skddc** [comment]
... in any case, if we add read status to the model, it'd be very easy to experiment with that, or even make it configurable.
