### ISSUE TITLE
Menu swiping not working in Chrome

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#63]
Swiping on the channel container area to open/close the menu works in Mobile Safari and Firefox, but not in Chrome.

**Comment by skddc** [comment]
Chrome desktop with mobile emulation actually does work for me, so it looks like a bug in my Chrome for Android.

**Comment by skddc** [comment]
Note: same issue in all of stable, beta and canary on Android.

**Comment by skddc** [comment]
I tried to add the swipe handlers to the `channel-container` component, but even there no swipes are even registered, while the `app-container` swipes work just fine as long as the `channel-container` isn't open. I'm kind of at the end of my abilities to debug this. @galfert Any ideas maybe?

**Comment by skddc** [comment]
Here's the best part, uncovered today:

In Safari, tapping the channel header doesn't work for opening/closing the menu, so it's exactly the other way around. :)

**Comment by galfert** [comment]
I found that at least in mobile Chrome the`overflow: auto` on the `.main` class (https://github.com/67P/hyperchannel/blob/9df59f07ff8e099371f5c3fc9d7d40b8e37b24a9/app/styles/_layout.scss#L13) is what prevents the swipe events.

Haven't checked Safari yet.

**Comment by galfert** [comment]
I was able to at least fix the Safari problem.

There seems to be a bug that requires an empty click handler on the `header` element in order for the `menu` action to get triggered  `¯\_(ツ)_/¯`

**Comment by galfert** [comment]
Here's the corresponding bug report in Hammer.js: https://github.com/hammerjs/hammer.js/issues/1065

**Comment by skddc** [comment]
> I was able to at least fix the Safari problem.

Yay!

> Here's the corresponding bug report in Hammer.js: hammerjs/hammer.js#1065

Cool. Looks like they kinda have to fix it asap, because everyone's running into it.

**Comment by galfert** [comment]
One of the contributors just commented on the issue:

> I think this is due to chrome making touchEvents passive by default. Ill try to find time to lookinto this and fix this week

\o/

For the meantime I created a temporary fix at #71.
