### ISSUE TITLE
ServiceWorker problem in FF (reloads many times)

### ISSUE THREAD

**Issue by skddc** [67P/hyperchannel#80]
I just deployed the SW-enabled `master` to https://hyperchannel.kosmos.org. Looks good in Chrome on my phone, but breaks horribly in FF stable on Linux for me. It thinks that the cache is outdated at least once, but sometimes going into an infinite loop, deleting caches and reloading the app endlessly.

**Comment by gregkare** [comment]
I'm getting the same infinite loop on Firefox stable (OS X)

**Comment by skddc** [comment]
I found out what the problem is (roughly): it's a bug in FF, dealing with multiple ServiceWorkers. The 5apps shim worker (which does literally nothing, it's just a shim with no code to enable install dialogs) "conflicts" with the caching worker in this case. Chrome handles it just fine, and I couldn't find anything in the cache worker code that could make it fail.

**Comment by skddc** [comment]
We could check out https://developers.google.com/web/tools/workbox/
