### ISSUE TITLE
Double colon when message starts with colon

### ISSUE THREAD

**Issue by galfert** [67P/hyperchannel#91]
When starting a message with a colon, it gets send with 2 colons. Hyperchannel itself only shows a single colon though.

E.g. sending `:)` shows `::)` in other clients.

**Comment by galfert** [comment]
I was checking out this bug and found that the messages are actually sent out to Sockethub correctly. So I think it's rather a problem in Sockethub itself.

@silverbucket any idea what might be going on here?

**Comment by skddc** [comment]
Just FYI: I could also reproduce this when posting a `:)` from Hyperchannel recently.
